### ISSUE TITLE
Not sure how to use/install

### ISSUE THREAD

**Issue by charlescbullock** [vanvught/rpidmx512-zip#1]
Hello!

I am new to Raspberry Pi's. I just got my first Pi. It's a Raspberry Pi 3 B+.

I am trying to install a software that allows me to receive Art-Net on the Pi, from my lighting console, and transmit it from the Pi into WS2812 or WS2811 LED strips.. The individually addressed LED strips.

​

I have one of each strip, and an external power supply for the WS2811's - as they take 12v.

​

I have found some code that has already been made for this application - I believe - here:
https://github.com/vanvught/rpidmx512

​

How do I install it??

Or boot into it?

I'm honestly not sure if it's an OS version, or if it's intended to run as a program on the Pi's Native OS.

Some more Raspberry Pi and DMX/Art-Net info can be found here:
http://www.raspberrypi-dmx.org/

I would assume, in this case, I'm looking to install the:
Art-Net 3 DMX Node / Pixel (WS28xx / SK6812) controller {SDCard}

files..

​

I have also been pointed to this file location:
https://github.com/vanvught/rpidmx512-zip/blob/master/rpi_circle_artnet_dmx.zip

But honestly - I'm kind of running in circles here.
Not going anywhere very quickly.

​

Any help would be GREATLY appreciated!!!!!

​

Thank you ALL!

Have a great day!

​

**Comment by vanvught** [comment]
> I have also been pointed to this file location:
https://github.com/vanvught/rpidmx512-zip/blob/master/rpi_circle_artnet_dmx.zip

Just unzip the file to an empty FAT formatted SDCard. 

In artnet.txt, set output=spi
In devices.txt, set led_type= and led_count=
See 
http://www.orangepi-dmx.org/raspberry-pi-art-net-dmx-out/configuration

**Comment by vanvught** [comment]
Please note that the Art-Net Ethernet pixel controller is also available for the Orange Pi Zero. This board is cheaper,  and has SPI flash on board. Hence the SDCard is just needed once.

**Comment by charlescbullock** [comment]
When I extract the contents in
https://github.com/vanvught/rpidmx512-zip/blob/master/rpi_circle_artnet_dmx.zip,
I get the following files:

bootcode.bin
config.txt
fixup.dat
kernel.img
kernel7.img
LICENCE.broadcom
start.elf

When I insert it into the Raspberry Pi 3 B+, I get the Color-Spectrum
Splash Screen with a lightning bolt in the top right.

Thank you SO MUCH for your input though!!!
I greatly appreciate it.

Do you have any other suggestions?

**Comment by vanvught** [comment]
Hi Chris, I have just sent a new zip file to your personal email address.

**Comment by vanvught** [comment]
The zip file sent is working; I need to update the Broadcom firmware in the zip files on Github
