### ISSUE TITLE
RDM Responder didn't boot on Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by covsh** [vanvught/rpidmx512-zip#4]
I see only Coloured splash screen and red LED blinking (4 times long, 4 short).
Other images works fine.

**Comment by vanvught** [comment]
Looking at the commit date, I can imagine that this .zip file does not have Broadcom firmware for the Pi 3 B+. Just copy the kernel?.img files to a working SDCard and it should be fine.

Please note that I am moving away from the Raspberry Pi boards. The next supported board is the Orange Pi Zero:

- Far better Ethernet implementation.
- Can boot from SPI flash; the SDCard is just needed once.
- With the SPI flash, all firmware configuration items are stored in SPI flash.
- Much cheaper.
- Easier for software maintenance 
- GPIO header is compatible with the Raspberry Pi header; RPi hardware can be used

**Comment by covsh** [comment]
> Looking at the commit date, I can imagine that this .zip file does not have Broadcom firmware for the Pi 3 B+. Just copy the kernel?.img files to a working SDCard and it should be fine.

Yep, that works. Thanks
