### ISSUE TITLE
rpi artnet circle dmx not booting on RPi 3B

### ISSUE THREAD

**Issue by jamesxsc** [vanvught/rpidmx512-zip#5]
I tried the fix in the last issue which was copying only the kernel files onto the SD, which didn't boot and with all the files on the card, the red LED stayed on on the pi and the green LED was falshing as were the ethernet port LEDs. I just copied the files to the card each time. Should I have imaged them? If not then how can I fix this.

Thanks

James

**Comment by vanvught** [comment]
Hi James,

I will look into it. But please note that I am moving away from the Raspberry Pi boards. The next supported board is the Orange Pi Zero:

- The OPi Zero has a far better Ethernet implementation compared with the RPi Models <=3.
- The OPi Zero has SPI flash; all settings can be stored in SPI flash, it boot from SPI flash.
- The OPi Zero has a full Art-Net 4 implementation.
- The OPi Zero has an unique remote configuration framework.
- The OPi Zero has better availability and is much cheaper. 
- The RPi add-on's are compatible with the OPi Zero GPIO header.

**Comment by jamesxsc** [comment]
Thanks for the quick reply. The next pi I buy will probably be an orange pi but right now I only have raspberries.

**Comment by vanvught** [comment]
Hi James, I have tested the firmware from GitHub and it is working fine for me. 

Please will you check your network.txt. The name_server= is a prerequisite for this firmware -> http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/network-configuration/ethernet
You can set it the same as the default_gateway.

- Arjan 

![Knipsel](https://user-images.githubusercontent.com/4319913/65835009-6e721500-e2e1-11e9-8d0a-975b2be12dfb.PNG)

**Comment by vanvught** [comment]
@jamesxsc Please will you give an update. Thanks, Arjan

**Comment by jamesxsc** [comment]
Sorry for the delay. I adjusted config.txt with some hdmi settingsto fix.
