### ISSUE TITLE
Should this work on a Raspberry Pi 4?

### ISSUE THREAD

**Issue by bardal** [vanvught/rpidmx512-zip#6]
I can't get it to boot. Have tried commenting/uncommenting the various HDMI lines  in config.txt but I just get a few green flashes from the Pi LEDs and a blank screen.

Same setup boots raspbian no issue.

**Comment by vanvught** [comment]
No. This is not going to work on the Raspberry Pi 4. The model 4 is pretty much overkill. 

Please see also https://github.com/vanvught/rpidmx512-zip/issues/5#issuecomment-536272513 For all new projects, the supported board is the Orange Pi Zero:

- The OPi Zero has a far better Ethernet implementation compared with the RPi Models <=3.
- The OPi Zero has SPI flash; all settings can be stored in SPI flash, it boot from SPI flash.
- The OPi Zero has a full Art-Net 4 implementation.
- The OPi Zero has an unique remote configuration framework.
- The OPi Zero has better availability and is much cheaper.
- The RPi add-on's are compatible with the OPi Zero GPIO header.

**Comment by bardal** [comment]
Thanks, I came to this via http://bitwizard.nl/shop/dmx which doesn't mention the Orange Pi, which to be honest I'd never heard of. I will suggest to them that they emphasise the Orange over the Raspberry. I've found an old Pi 2 that was gathering dust so will try to get it working on that and then look at buying an OPi Zero.

**Comment by vanvught** [comment]
The Raspberry Pi Model 2 should work fine. But you would have more fun(ctionality) with Orange Pi Zero.

**Comment by bardal** [comment]
So, with the Pi v2 I get 3 lines of boot info. 
Last line "Device UUID : ..."
The green LED is flashing consistently.
Does that mean I'm up and running?

**Comment by vanvught** [comment]
> The green LED is flashing consistently.

That's good.

> Does that mean I'm up and running?

Yes.

**Comment by bardal** [comment]
Great, now I have to work out how to get it show up in QLC+ on my PC....

**Comment by ImNoahDev** [comment]
Does the Bitwizard board work on the orange pi one? Alternatively what image should I use for a pi2 or pi(B) and the Bitwizard board for ethernet Artnet to dmx
