### ISSUE TITLE
Raspberry pi ArtNet Ethernet (1x DMX / RDM / Pixel Controller 4 Universes)

### ISSUE THREAD

**Issue by bstivic** [vanvught/rpidmx512-zip#7]
You have Removed Art-Net Ethernet firmware, because, as you said moved to orange pi and i understand completely. 
But as borders are closed, i cant find orange pi that is not shipped from china and must use raspberry pi 2 in project. Can you send me old https://github.com/vanvught/rpidmx512-zip/blob/master/rpi_circle_artnet_dmx.zip?raw=true file to test it on rpi 2?

Best Regards,
Branimir

**Comment by vanvught** [comment]
Hi Branimir

The last version is here https://github.com/vanvught/rpidmx512-zip/tree/adc13127d8454129e867214b0bf586afc762b10b

Greetings, Arjan
